mantis:
    base_url: "http://localhost:8080/mantis"
    api_token: "VoZ4d_uyq7fX1mv5DZ4zqhyJbCL3peMv"
    project_id: 1
    time_zone: "Asia/Kolkata"
    issue_fields: "id, summary, description, reporter.name,reporter.email,handler.name,handler.email, status.label, resolution.label, priority.label, severity.label"
    work_notes_fields: "id, reporter.name,reporter.email, text"
    page_size: 50

    #FilterId defined in Mantis to skip closed/resolved in response for Mantis API all issues call.
    #Comment this to fetch updated issues list from DB in given range and then extract only those issues using Mantis API call
    #filter_id: 12


mysql:
    host: "localhost"
    user: "root"
    password: ""
    database: "bugtracker"
    charset: "utf8mb4"

msmq:
    queue: ".\\Private$\\mantis_notification_queue"

logging:
    logging_file: 'logs/mantis_worknotes_notification.log'
    logging_level: 'DEBUG'
    logging_format: '%(asctime)s :: %(levelname)s :: %(message)s :: Message Source:- file-"%(module)s" & method-"%(funcName)s"'

attachment_base_dir: "attachments"

