mantis:
    base_url: "http://localhost:8086/mantis"
    api_token: "wd3tBpvAmpVRfqM8_nPg7T3cxxBw4KMs"
    project_id: 1
    time_zone: "Asia/Kolkata"
    issue_fields: "id, summary, description, reporter.name,reporter.email,handler.name,handler.email, status.label, resolution.label, priority.label, severity.label"
    work_notes_fields: "id, reporter.name,reporter.email, text"
    page_size: 50

mysql:
    host: "localhost"
    user: "root"
    password: "root"
    database: "bugtracker"
    charset: "utf8mb4"

msmq:
    queue: ".\\Private$\\myqueue"

logging:
    logging_file: 'logs/mantis_worknotes_notification.log'
    logging_level: 'DEBUG'
    logging_format: '%(asctime)s :: %(levelname)s :: %(message)s :: Message Source:- file-"%(module)s" & method-"%(funcName)s"'

attachment_base_dir: "attachments"
issue_label_formatter: 'Issue Id - {Issue Id} :: {Issue Description}'
note_label_formatter: 'Issue Id - {Issue Id} :: {Issue Description} :: {Work Note Text}'


email:
    host: "smtp-mail.outlook.com"
    port: 587
    from_email : "sachinkumarmantisbt@outlook.com"
    to_email: "sachinkumar27demon@gmail.com"
    password : "Sachin@12345"

