mantis:
    base_url: "http://localhost:8080/mantis"
    api_token: "VoZ4d_uyq7fX1mv5DZ4zqhyJbCL3peMv"
    project_id: 1
    time_zone: "Asia/Kolkata"
    issue_fields: "id, summary, description, reporter.name,reporter.email,handler.name,handler.email, status.label, resolution.label, priority.label, severity.label"
    work_notes_fields: "id, reporter.name,reporter.email, text"
    page_size: 50

mysql:
    host: "localhost"
    user: "root"
    password: ""
    database: "bugtracker"
    charset: "utf8mb4"

msmq:
    queue: ".\\Private$\\mantis_notification_queue"

logging:
    logging_file: 'logs/mantis_worknotes_notification.log'
    logging_level: 'DEBUG'
    logging_format: '%(asctime)s :: %(levelname)s :: %(message)s :: Message Source:- file-"%(module)s" & method-"%(funcName)s"'

attachment_base_dir: "attachments"
issue_label_formatter: 'Issue Id - {Issue Id} :: {Issue Description}'
note_label_formatter: 'Issue Id - {Issue Id} :: {Issue Description} :: {Work Note Text}'

